Repository ergon/airlock-helm-charts, pull requests merged in 2020-05, with the labels that each got.

#21 Add HorizontalPodAutoscaler template
  charts/microgateway/README.md
  charts/microgateway/templates/hpa.yaml
  charts/microgateway/values.yaml
Labels: enhancement

#27 Bugfix issue #26: Document that destinationCACertificate must be dele…
  charts/microgateway/README.md
  charts/microgateway/README.md.gotmpl
Labels: bug, documentation

#28 Update README.md
  charts/microgateway/README.md
Labels: documentation

#29 Docu review
  charts/microgateway/Chart.yaml
  charts/microgateway/README.md
  charts/microgateway/README.md.gotmpl
  charts/microgateway/values.yaml
Labels: documentation

#25 Add HorizontalPodAutoscaler template
  charts/microgateway/Chart.yaml
  charts/microgateway/README.md
  charts/microgateway/README.md.gotmpl
  charts/microgateway/templates/hpa.yaml
  charts/microgateway/values.yaml
Labels: enhancement

#32 CI Files update
  charts/microgateway/ci/testing-values.yaml
Labels: enhancement

#41 Update049
  charts/microgateway/Chart.yaml
  charts/microgateway/README.md
  charts/microgateway/README.md.gotmpl
  charts/microgateway/ci/testing-values.yaml
  charts/microgateway/templates/_helpers.tpl
  charts/microgateway/templates/configmap.yaml
  charts/microgateway/values.yaml
Labels: bug, documentation, enhancement
